// app/layout.tsx
import type { Metadata } from "next";
import Navbar from "@/components/Header";
import "./globals.css";
import { AuthProvider } from '@/components/Auth/AuthProvider';
import { ProgressProvider } from '@/components/Progress/ProgressProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ProgressProvider>
              <Navbar />
            {children}
          </ProgressProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
